fx_version 'cerulean'
game 'gta5'
this_is_a_map 'yes'
files {
	'common/*.meta'
}
data_file 'DLC_ITYP_REQUEST' 'stream/def_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/farm_storage.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/garage_mirror.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/indust_02_metadata_013_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/kpri_dets.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/kpri_mirror_v2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/kpri_propslib.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/kpri_propslib2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_bush.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_construction.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_electrical.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_fences.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_minigame.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_storage.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/v_traffic_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vg_cc_props.ytyp'
