Config.DebugCircle = true -- enable if you want to see the circle marker coords & size with  command below
Config.Command = 'lab'     -- /lab

Config.LabHelpMarker = true

Config.Anti_AFK = true
Config.Check_AFK = {min = 2, max = 5} -- in minute

function canCollect(data) -- if you want to do some additional check before collect, you can place your code here (client side)
    return true
end

function canProcess(data) -- if you want to do some additional check before process, you can place your code here (client side)
    return true
end

Config.Labs = {
    CollectPoints = {
        {
            item        = "fgpfive",
            item_label  = "Weapon Parts",
            reward      = {min = 3, max = 3},
            pos         = vector4(-690.2286, 839.9281, 3.8154, 1.0),
            size        = 3.00,
            delay = 10,
        },
        {
            item        = "fgpfour",
            item_label  = "Weapon Barrel",
            reward      = {min = 3, max = 3},
            pos         = vector4(-690.2308, 835.5378, 3.8154, 1.0),
            size        = 3.00,
            delay = 10,
        },
        {
            item        = "fgpthree",
            item_label  = "Weapon Mag",
            reward      = {min = 3, max = 3},
            pos         = vector4(-694.2203, 835.7684, 3.5167, 1.0),
            size        = 3.00,
            delay = 10,
        },
        {
            item        = "fgptwo",
            item_label  = "Weapon Body",
            reward      = {min = 3, max = 3},
            pos         = vector4(-694.2158, 831.8341, 3.5167, 1.0),
            size        = 3.00,
            delay = 10,
        },
        {
            item        = "fgpone",
            item_label  = "Weapon Grip",
            reward      = {min = 3, max = 3},
            pos         = vector4(-691.4517, 820.4220, 3.8154, 1.0),
            size        = 3.00,
            delay = 10,
        },
        {
            item        = "raweedkos",
            item_label  = "Harvest Weed",
            reward      = {min = 6, max = 6},
            pos         = vector4(584.1235, 2329.5371, 11.0330, 1.0),
            size        = 5.00,
            delay = 10,
        },
        {
            item        = "raweedkos",
            item_label  = "Harvest Weed",
            reward      = {min = 6, max = 6},
            pos         = vector4(578.6333, 2329.4451, 11.0328, 1.0),
            size        = 5.00,
            delay = 10,
        },
        {
            item        = "weedrrnewewx",
            item_label  = "Harvest Weed",
            reward      = {min = 4, max = 12},
            pos         = vector4(211.1788, 144.4163, 13.7018, 1.0),
            size        = 5.00,
            delay = 5,
        },
        {
            item        = "newromxm",
            item_label  = "Mushrooms",
            reward      = {min = 4, max = 4},
            pos         = vector4(-1280.6823, 652.6575, 22.1481, 1.0),
            size        = 6.50,
            delay = 10,
        },
        {
            item        = "k2drgxnew",
            item_label  = "2k jail",
            reward      = {min = 4, max = 4},
            pos         = vector4(2251.4380, 2147.0054, 10.9509, 1.0),
            size        = 4.50,
            delay = 10,
        },
        {
            item        = "purpdustlc",
            item_label  = "Purp Dust",
            reward      = {min = 4, max = 4},
            pos         = vector4(-1324.4628, 162.8547, -1.7783, 1.0),
            size        = 8.50,
            delay = 10,
        },
        {
            item        = "lsddrop",
            item_label  = "LSD Liquid",
            reward      = {min = 4, max = 4},
            pos         = vector4(1393.7582, 244.8508, 5.8503, 1.0),
            size        = 5.50,
            delay = 10,
        },
        {
            item        = "meth",
            item_label  = "Raw Meth",
            reward      = {min = 4, max = 4},
            pos         = vector4(-255.6717, 578.9127, 1.7340, 1.0),
            size        = 6.00,
            delay = 10,
        },
    },
    ProcessPoints = {
        {
            item        = "runtzbagog",
            item_label  = "weed pooch",
            reward      = {min = 100, max = 100},
            pos         = vector4(-932.1100, -1177.8241, 4.0243, 1.0),
            size        = 3.50,
            recipe = {
                weednugskos  = {qty = 300, willremove = true},
                pooch_bag  = {qty = 100, willremove = true},
            },
            delay = 45,
        },
        {
            item        = "runtzbagog",
            item_label  = "weed pooch",
            reward      = {min = 100, max = 100},
            pos         = vector4(555.2679, 2319.1394, 16.8783, 1.0),
            size        = 3.00,
            recipe = {
                weednugskos  = {qty = 300, willremove = true},
                pooch_bag  = {qty = 100, willremove = true},
            },
            delay = 45,
        },
        {
            item        = "weed_haze_pooch",
            item_label  = "weed pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(176.1707, 2059.8420, 11.9170, 1.0),
            size        = 7.00,
            recipe = {
                weedhazenew  = {qty = 6, willremove = true},
                hazepooch_bag  = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "runtzbagog",
            item_label  = "weed pooch",
            reward      = {min = 100, max = 100},
            pos         = vector4(551.5970, 2322.7793, 16.8783, 1.0),
            size        = 3.00,
            recipe = {
                weednugskos  = {qty = 300, willremove = true},
                pooch_bag  = {qty = 100, willremove = true},
            },
            delay = 45,
        },
        {
            item        = "runtzbagog",
            item_label  = "weed pooch",
            reward      = {min = 100, max = 100},
            pos         = vector4(553.2900, 2314.5767, 16.8783, 1.0),
            size        = 3.00,
            recipe = {
                weednugskos  = {qty = 300, willremove = true},
                pooch_bag  = {qty = 100, willremove = true},
            },
            delay = 45,
        },
        {
            item        = "pooch_whippets",
            item_label  = "Whippets",
            reward      = {min = 1, max = 1},
            pos         = vector4(437.0203, -1884.9415, 30.7385, 1.0),
            size        = 4.50,
            recipe = {
                nitrowhip  = {qty = 6, willremove = true},
                whippetscartridges  = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "double_cup",
            item_label  = "DoubleCup",
            reward      = {min = 1, max = 1},
            pos         = vector4(1002.3427, -2319.8652, 29.5584, 1.0),
            size        = 6.00,
            recipe = {
                lean_bottle = {qty = 6, willremove = true},
                bbbottle = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "lsdtab",
            item_label  = "LSD tabs",
            reward      = {min = 1, max = 1},
            pos         = vector4(-372.8662, 232.8403, 65.7975, 1.0),
            size        = 6.00,
            recipe = {
                lsddrop = {qty = 6, willremove = true},
                fabric = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "lsdtab",
            item_label  = "LSD tabs",
            reward      = {min = 1, max = 1},
            pos         = vector4(-1086.9166, 1562.3993, 1.8988, 1.0),
            size        = 3.00,
            recipe = {
                lsddrop = {qty = 6, willremove = true},
                fabric = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "lsdtab",
            item_label  = "LSD tabs",
            reward      = {min = 1, max = 1},
            pos         = vector4(-1094.7964, 1563.5074, 1.8988, 1.0),
            size        = 4.00,
            recipe = {
                lsddrop = {qty = 6, willremove = true},
                fabric = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
	    item        = "hero_pooch",
            item_label  = "Heroin Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector(1766.2396, -1611.8815, 111.3046, 1.0),
            size        = 4.50,
            recipe = {
		heroin    = {qty = 6, willremove = true},
                pooch_bag   = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "coke_pooch",
            item_label  = "Coke Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(-1140.3330, -1291.3615, -2.6643, 1.0),
            size        = 7.00,
            recipe = {
                icoke = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "pooch_romm",
            item_label  = "Mushrooms Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(-279.4661, -2671.2532, -5.7163, 1.0),
            size        = 8.00,
            recipe = {
                rom = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "oxycodone",
            item_label  = "Opium Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(1763.1758, -1593.3784, 111.3045, 1.0),
            size        = 4.50,
            recipe = {
                opium = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "oxycodone",
            item_label  = "Opium Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(-225.2139, -2656.3826, 5.0003, 1.0),
            size        = 3.50,
            recipe = {
                opium = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "newdrugxll",
            item_label  = "Molly Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(533.1063, -3054.1892, 0.1031, 1.0),
            size        = 5.00,
            recipe = {
                pcpppcp = {qty = 7, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "spfentpooch",
            item_label  = "SuperFent Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(913.9556, -1503.5688, 30.2155, 1.0),
            size        = 6.00,
            recipe = {
                sdemiaroiuds = {qty = 6, willremove = true},
		rawfent = {qty = 1, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "finxsdwax",
            item_label  = "Wax Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(-194.3554, -1699.6597, 25.0342, 1.0),
            size        = 7.50,
            recipe = {
                nuggsxawax = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "spicalodrgbw",
            item_label  = "k2 Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(1524.7860, 931.5200, 18.6197, 1.0),
            size        = 7.00,
            recipe = {
                k2drgxnew = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "tuzi_pooch",
            item_label  = "Tusi Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(-1659.8329, -1059.5332, 12.2466, 1.0),
            size        = 6.00,
            recipe = {
                dpil2 = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "cokef_pooch",
            item_label  = "Extra Coke Pooch",
            reward      = {min = 200, max = 200},
            pos         = vector4(102.0659, 2054.5627, 17.6479, 1.0),
            size        = 3.00,
            recipe = {
                coke_pooch = {qty = 100, willremove = true},
                rawfent = {qty = 10, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "wwbagogx",
            item_label  = "process weed bag",
            reward      = {min = 100, max = 100},
            pos         = vector4(194.6225, -236.2221, 53.0705, 1.0),
            size        = 5.00,
            recipe = {
                weednugsygsx = {qty = 300, willremove = true},
                pooch_bag = {qty = 100, willremove = true},
            },
            delay = 45,
        },
        {
            item        = "oxycodonectch",
            item_label  = "process pain meds",
            reward      = {min = 1, max = 1},
            pos         = vector4(-123.8188, 2142.2378, 15.4537, 1.0),
            size        = 5.00,
            recipe = {
                icoke = {qty = 10, willremove = true},
                rom = {qty = 1, willremove = true},
            },
            delay = 7,
        },
        {
            item        = "weednugskos",
            item_label  = "Trim Grams",
            reward      = {min = 6, max = 7},
            pos         = vector4(-927.5554, -1174.6344, -1.8971, 1.0),
            size        = 4.50,
            recipe = {
                raweedkos = {qty = 6, willremove = true},
                trimtoolkosxx = {qty = 1, willremove = false},
            },
            delay = 5,
        },
        {
            item        = "wwgram1",
            item_label  = "WW Weed",
            reward      = {min = 10, max = 10},
            pos         = vector4(1560.7950, 830.7231, 17.3725, 1.0),
            size        = 3.00,
            recipe = {
                rawww1 = {qty = 10, willremove = true},
                wwtrimtool = {qty = 1, willremove = false},
            },
            delay = 3,
        },
        {
            item        = "oxi_pooch",
            item_label  = "Oxi Pooch",
            reward      = {min = 10, max = 10},
            pos         = vector4(921.6405, -1508.8319, 30.2155, 1.0),
            size        = 5.00,
            recipe = {
                hyacid = {qty = 33, willremove = true},
                ratpoison = {qty = 1, willremove = true},
                pooch_bag = {qty = 10, willremove = true},
            },
            delay = 35,
        },
        {
            item        = "newdrugxll",
            item_label  = "Shroom Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(1085.1112, 1926.0813, 18.0596, 1.0),
            size        = 7.00,
            recipe = {
                newromxm = {qty = 3, willremove = true},
                rawfent = {qty = 3, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "poochdilemama",
            item_label  = "RED Shroom Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(-730.5209, 2391.5854, 21.3757, 1.0),
            size        = 8.00,
            recipe = {
                newromxm = {qty = 4, willremove = true},
                blood_sample = {qty = 1, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "otherdrugnewxx",
            item_label  = "Lased Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(5211.6899, -5126.0459, 5.2100, 1.0),
            size        = 4.00,
            recipe = {
                newromxm = {qty = 6, willremove = true},
                gmrmollynew = {qty = 1, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "weednugsygsx",
            item_label  = "Trim Grams",
            reward      = {min = 6, max = 7},
            pos         = vector4(166.4191, -234.0275, 49.0553, 1.0),
            size        = 5.00,
            recipe = {
                rawweedygx = {qty = 6, willremove = true},
                trimtoolygxxx = {qty = 1, willremove = false},
            },
            delay = 5,
        },
        {
            item        = "otherdrugnewxxnew",
            item_label  = "Lased Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(5212.1060, -5131.0327, 5.2099, 1.0),
            size        = 4.00,
            recipe = {
                newromxm = {qty = 10, willremove = true},
                gmrmollytwo = {qty = 1, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "bottle_xanaxnew",
            item_label  = "xanax",
            reward      = {min = 1, max = 1},
            pos         = vector(-270.6662, -2681.9451, -5.7094, 1.0),
            size        = 6.50,
            recipe = {
                rawfent  = {qty = 6, willremove = true},
                medbottle = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
	    item        = "meth_poooch",
            item_label  = "Meth Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(908.0281, -893.4930, 19.1291, 1.0),
            size        = 7.50,
            recipe = {
		meth = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "fentanylblues",
            item_label  = "Fentanyl Blues",
            reward      = {min = 120, max = 120},
            pos         = vector4(1169.6292, -0.8919, 14.4846, 1.0),
            size        = 2.00,
            recipe = {
                bluesbrick  = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "double_cup",
            item_label  = "BulkLean Pack",
            reward      = {min = 330, max = 330},
            pos         = vector4(600.6582, 267.7846, 4.7296, 1.0),
            size        = 3.00,
            recipe = {
                bulkc  = {qty = 1, willremove = true},
                ebot  = {qty = 5, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "fakemoney",
            item_label  = "Fake Money",
            reward      = {min = 500000, max = 500000},
            pos         = vector4(1466.7351, 1944.7328, 15.7191, 1.0),
            size        = 3.30,
            recipe = {
                fakem  = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 11, max = 11},
            pos         = vector4(945.3588, -201.6368, 78.2920, 1.0),
            size        = 4.50,
            recipe = {
                icoke  = {qty = 33, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 11, willremove = true},
            },
            delay = 15,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(140.9677, -2100.1587, 17.0432, 1.0),
            size        = 3.00,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(1603.0769, 2136.8582, 30.3263, 1.0),
            size        = 2.80,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(62.5925, -2044.9254, 17.0432, 1.0),
            size        = 2.00,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(72.56, -1997.24, 17.0432, 1.0),
            size        = 2.00,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(44.35, -2027.81, 17.0432, 1.0),
            size        = 2.00,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(81.46, -2057.97, 17.0432, 1.0),
            size        = 2.00,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "double_cup",
            item_label  = "DoubleCup",
            reward      = {min = 1, max = 1},
            pos         = vector4(53.99, -1980.18, 17.0432, 1.0),
            size        = 3.00,
            recipe = {
                lean_bottle = {qty = 6, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "coke_pooch",
            item_label  = "Coke Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(91.29, -2012.59, 17.04, 1.0),
            size        = 2.80,
            recipe = {
                icoke = {qty = 6, willremove = true},
                pooch_bag = {qty = 1, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(132.57, -1999.93, 17.0432, 1.0),
            size        = 2.00,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "crackpooch3000",
            item_label  = "Cook Crack",
            reward      = {min = 33, max = 33},
            pos         = vector4(107.97, -2025.09, 17.0432, 1.0),
            size        = 2.00,
            recipe = {
                icoke  = {qty = 100, willremove = true},
                bakingsoda  = {qty = 1, willremove = true},
                pyrex  = {qty = 1, willremove = true},
                cookingpod  = {qty = 1, willremove = true},
                pooch_bag  = {qty = 33, willremove = true},
            },
            delay = 5,
        },
        {
            item        = "hero_pooch",
            item_label  = "Heroin Pooch",
            reward      = {min = 1, max = 1},
            pos         = vector4(111.03, -1986.97, 17.0432, 1.0),
            size        = 3.60,
            recipe = {
                heroin    = {qty = 6, willremove = true},
                pooch_bag   = {qty = 1, willremove = true},
            },
            delay = 5,
        },
    },
}
