Config = {
    requiredCops = 0,
    npcFightOnReject = false,
    cooldown = 1,
    maxCustomerCout = 1,
    ExpriencePerCustomer = 10,
    bossDealerLevel = 300,
    hoodDealerLevel = 150,
    deliveryFees = 1240,

    grades = {
        [0] = 'Novice Dealer',
        [30] = 'Associate Dealer',
        [60] = 'Recruit Dealer',
        [90] = 'Affiliate Dealer',
        [120] = 'Soldier Dealer',
        [150] = 'Hood Dealer',
        [200] = 'Lieutenants Dealer',
        [250] = 'Underboss Dealer',
        [300] = 'Capo Dealer',
        [400] = 'Drug Lord Dealer',
        [700] = 'Boss Dealer',
        [1000] = 'Kingpin Dealer',
    },

    locations = {
        {coords = vector4(1281.5291, 1907.0094, 82.1487, 84.8877)},
        {coords = vector4(-2956.4167, 442.7626, 15.2656, 80.1152)},
        {coords = vector4(1014.9907, -2448.1069, 28.5175, 183.0571)},
        {coords = vector4(1260.7478, -335.2941, 69.0821, 116.3797)},
        {coords = vector4(12.8917, 543.1086, 175.9561, 31.2749)},
        {coords = vector4(2496.1980, 1593.3744, 32.7203, 252.8748)},
        {coords = vector4(-1724.2273, -905.6872, 7.6716, 284.3198)},
        {coords = vector4(-1523.0112, -31.3064, 57.2837, 352.4021)},
        {coords = vector4(-1282.9197, 300.6776, 64.8939, 150.5804)},
        {coords = vector4(126.9961, 640.5232, 207.3945, 57.3043)},
        {coords = vector4(929.6826, 56.7378, 81.1022, 90.9314)},
        {coords = vector4(1244.9307, -600.1117, 69.4329, 269.1968)},
        {coords = vector4(1449.5695, -1726.0419, 67.8731, 121.8842)},
        {coords = vector4(1262.4642, -2562.1365, 42.7177, 280.7180)},
        {coords = vector4(978.5114, -2503.5569, 28.4523, 319.6975)},
        {coords = vector4(2670.2764, 3257.1787, 55.2405, 200.8188)},
        {coords = vector4(2573.1804, 4274.6191, 41.8425, 251.2960)},
        {coords = vector4(1951.7596, 3758.4331, 32.2037, 26.3861)},
        {coords = vector4(1528.4264, 3773.4983, 34.5086, 197.0245)},
        {coords = vector4(1028.2219, 2658.7676, 39.5158, 18.0323)},
        {coords = vector4(-941.4478, 590.9712, 101.0015, 123.9265)},
        {coords = vector4(-1454.1180, 116.1479, 52.2385, 269.5823)},
        {coords = vector4(-269.5932, -890.4069, 31.2197, 74.2103)},
        {coords = vector4(-53.4290, -216.7943, 45.4177, 155.2673)},
        {coords = vector4(523.9078, -151.1500, 57.4784, 101.8190)},
        {coords = vector4(254.6331, -1029.9025, 29.2255, 189.4513)},
        {coords = vector4(384.8477, -1541.2291, 29.3245, 141.3902)},
        {coords = vector4(718.9854, -2078.1289, 29.2897, 359.7947)},
        {coords = vector4(264.0038, -2501.9375, 6.4356, 279.8570)},
        {coords = vector4(486.2114, -3049.7600, 6.0816, 347.4895)},
        {coords = vector4(1436.6787, -1494.5535, 63.2244, 151.5076)},
        {coords = vector4(1141.0936, -971.8438, 46.7346, 260.5724)},
        {coords = vector4(1024.8385, -516.1481, 61.0294, 207.4136)},
        {coords = vector4(443.1210, -688.9399, 28.5998, 8.0000)},
        {coords = vector4(-371.8857, -827.5117, 31.5019, 178.9743)},
        {coords = vector4(-664.8674, -1217.5496, 11.8170, 8.8947)},
        {coords = vector4(-580.2781, -1072.8594, 22.2595, 181.4986)},
        {coords = vector4(-595.6351, -1144.0066, 22.2652, 302.4781)},
        {coords = vector4(-93.0045, -702.8373, 34.7748, 101.5775)},
    },

    ToogleKeys = {
		{key = "F", value = 23},
		{key = "E", value = 38},
		{key = "H", value = 74},
	},

    account = 'black_money', --change to 'money' if you want
    drugs = {
    ['pooch_romm'] = 775,
    ['double_cup'] = 775,
    ['pooch_whippets'] = 725,
    ['bottle_xanaxnew'] = 785,
    ['hero_pooch'] = 785,
    ['oxycodone'] = 745,
    ['coke_pooch'] = 765,
    ['meth_poooch'] = 1075,
    ['crackpooch3000'] = 795,
    ['lsdtab'] = 765,
    ['oxi_pooch'] = 705,
    ['runtzbagog'] = 725,
    ['wwbagogx'] = 725,
    ['prjbaby1'] = 725,
    ['tuzi_pooch'] = 745,
    ['finxsdwax'] =772,
    ['newdrugxll'] = 742,
    },

    drugsDealer = {
        'double_cup',
        'pooch_whippets',
        'bottle_xanaxnew',
        'meth_poooch',
        'crackpooch3000',
        'lsdtab',
        'oxi_pooch',
        'runtzbagog',
        'wwbagogx',
        --add as much as you want
    },

    cityPoint = vector3(5028.7383, -5101.8418, 6.0018), --set cityPoint to false to disable
    notify = {
        title = 'Drugs',
        nodrugs = 'You don\'t have any drugs to sell',
        cooldown = '~r~Please wait some time',
        toofar = '~r~You\'re too far from the city',
        cops = '~r~There\'s no cops in the city',
        searching = 'You\'re searching for clients for ~g~',
        abort = '~r~Client has resigned from the order',
        notfound = '~r~There\'s no nearby clients',
        approach = 'Your client is approaching',
        found = '~g~You\'ve found client on ~y~',
        press = 'Press ~INPUT_PICKUP~ to ~y~sell',
        reject = '~r~Go sell this bullshit to yo bitch.',
        vehicle = '~r~You\'ve to leave vehicle to sell',
        sold = '~g~You\'ve sold ~y~x%s of %s ~g~for %s$',
        client = '~g~Your client ~n~~r~want\'s to buy x%s %s',
        dealer = '~g~Hey Boss ! ~n~~r~ I need x%s %s',
        hood = '~g~Hey Hood ! ~n~~r~ I need x%s %s',
        police_notify_title = 'Police dispatch',
        police_notify_subtitle = '~r~Drugs sell',
    },
    pedlist = {
        'ig_abigail',
        'csb_abigail',
        'u_m_y_abner',
        'a_m_m_afriamer_01',
        'ig_mp_agent14',
        'csb_mp_agent14',
        'csb_agent',
        's_f_y_airhostess_01',
        's_m_y_airworker',
        'u_m_m_aldinapoli',
        'ig_amandatownley',
        'cs_amandatownley',
        's_m_y_ammucity_01',
        's_m_m_ammucountry',
        'ig_andreas',
        'cs_andreas',
        'csb_anita',
        'u_m_y_antonb',
        'csb_anton',
        'g_m_m_armboss_01',
        'g_m_m_armgoon_01',
        'g_m_y_armgoon_02',
        'g_m_m_armlieut_01',
        'mp_s_m_armoured_01',
        's_m_m_armoured_01',
        's_m_m_armoured_02',
        's_m_y_armymech_01',
        'ig_ashley',
        'cs_ashley',
        's_m_y_autopsy_01',
        's_m_m_autoshop_01',
        's_m_m_autoshop_02',
        'ig_money',
        'csb_money',
        'g_m_y_azteca_01',
        'g_m_y_ballaeast_01',
        'g_m_y_ballaorig_01',
        'g_f_y_ballas_01',
        'ig_ballasog',
        'csb_ballasog',
        'g_m_y_ballasout_01',
        'u_m_m_bankman',
        'ig_bankman',
        'cs_bankman',
        's_m_y_barman_01',
        'ig_barry',
        'cs_barry',
        's_f_y_bartender_01',
        'u_m_y_baygor',
        's_f_y_baywatch_01',
        's_m_y_baywatch_01',
        'a_f_m_beach_01',
        'a_f_y_beach_01',
        'a_m_m_beach_01',
        'a_m_o_beach_01',
        'a_m_y_beach_01',
        'a_m_m_beach_02',
        'a_m_y_beach_02',
        'a_m_y_beach_03',
        'a_m_y_beachvesp_01',
        'a_m_y_beachvesp_02',
        'ig_benny',
        'ig_bestmen',
        'ig_beverly',
        'cs_beverly',
        'a_f_m_bevhills_01',
        'a_f_y_bevhills_01',
        'a_m_m_bevhills_01',
        'a_m_y_bevhills_01',
        'a_f_m_bevhills_02',
        'a_f_y_bevhills_02',
        'a_m_m_bevhills_02',
        'a_m_y_bevhills_02',
        'a_f_y_bevhills_03',
        'a_f_y_bevhills_04',
        'u_m_m_bikehire_01',
        'u_f_y_bikerchic',
        'mp_f_boatstaff_01',
        'mp_m_boatstaff_01',
        'a_f_m_bodybuild_01',
        's_m_m_bouncer_01',
        'ig_brad',
        'cs_brad',
        'a_m_y_breakdance_01',
        'ig_bride',
        'csb_bride',
        'u_m_y_burgerdrug_01',
        'csb_burgerdrug',
        's_m_y_busboy_01',
        'a_m_y_busicas_01',
        'a_f_y_business_01',
        'a_m_m_business_01',
        'a_m_y_business_01',
        'a_f_m_business_02',
        'a_f_y_business_02',
        'a_m_y_business_02',
        'a_f_y_business_03',
        'a_m_y_business_03',
        'a_f_y_business_04',
        's_m_o_busker_01',
        'ig_car3guy1',
        'csb_car3guy1',
        'ig_car3guy2',
        'csb_car3guy2',
        'cs_carbuyer',
        'ig_casey',
        'cs_casey',
        's_m_m_ccrew_01',
        's_m_y_chef_01',
        'ig_chef2',
        'csb_chef2',
        'ig_chef',
        'csb_chef',
        's_m_m_chemsec_01',
        'g_m_m_chemwork_01',
        'g_m_m_chiboss_01',
        'g_m_m_chicold_01',
        'g_m_m_chigoon_01',
        'g_m_m_chigoon_02',
        'csb_chin_goon',
        'u_m_y_chip',
        's_m_m_ciasec_01',
        'mp_m_claude_01',
        'ig_clay',
        'cs_clay',
        'ig_claypain',
        'ig_cletus',
        'csb_cletus',
        's_m_y_clown_01',
        's_m_m_cntrybar_01',
        'u_f_y_comjane',
        's_m_y_construct_01',
        's_m_y_construct_02',
        'u_f_m_corpse_01',
        'u_f_y_corpse_02',
        'ig_chrisformage',
        'cs_chrisformage',
        'csb_customer',
        'u_m_y_cyclist_01',
        'a_m_y_cyclist_01',
        'ig_dale',
        'cs_dale',
        'ig_davenorton',
        'cs_davenorton',
        's_m_y_dealer_01',
        'cs_debra',
        'ig_denise',
        'cs_denise',
        'csb_denise_friend',
        'ig_devin',
        'cs_devin',
        's_m_y_devinsec_01',
        'a_m_y_dhill_01',
        'u_m_m_doa_01',
        's_m_m_dockwork_01',
        's_m_y_dockwork_01',
        's_m_m_doctor_01',
        'ig_dom',
        'cs_dom',
        's_m_y_doorman_01',
        'a_f_m_downtown_01',
        'a_m_y_downtown_01',
        'ig_dreyfuss',
        'cs_dreyfuss',
        'ig_drfriedlander',
        'cs_drfriedlander',
        'mp_f_deadhooker',
        's_m_y_dwservice_01',
        's_m_y_dwservice_02',
        'a_f_m_eastsa_01',
        'a_f_y_eastsa_01',
        'a_m_m_eastsa_01',
        'a_m_y_eastsa_01',
        'a_f_m_eastsa_02',
        'a_f_y_eastsa_02',
        'a_m_m_eastsa_02',
        'a_m_y_eastsa_02',
        'a_f_y_eastsa_03',
        'u_m_m_edtoh',
        'a_f_y_epsilon_01',
        'a_m_y_epsilon_01',
        'a_m_y_epsilon_02',
        'mp_m_exarmy_01',
        'ig_fabien',
        'cs_fabien',
        's_f_y_factory_01',
        's_m_y_factory_01',
        'g_m_y_famca_01',
        'mp_m_famdd_01',
        'g_m_y_famdnf_01',
        'g_m_y_famfor_01',
        'g_f_y_families_01',
        'a_m_m_farmer_01',
        'a_f_m_fatbla_01',
        'a_f_m_fatcult_01',
        'a_m_m_fatlatin_01',
        'a_f_m_fatwhite_01',
        'ig_fbisuit_01',
        'cs_fbisuit_01',
        's_f_m_fembarber',
        'u_m_m_fibarchitect',
        'u_m_y_fibmugger_01',
        's_m_m_fiboffice_01',
        's_m_m_fiboffice_02',
        'mp_m_fibsec_01',
        's_m_m_fibsec_01',
        'u_m_m_filmdirector',
        'u_m_o_filmnoir',
        'u_m_o_finguru_01',
        's_m_y_fireman_01',
        'a_f_y_fitness_01',
        'a_f_y_fitness_02',
        'ig_floyd',
        'cs_floyd',
        'csb_fos_rep',
        'ig_g',
        's_m_m_gaffer_01',
        's_m_y_garbage',
        's_m_m_gardener_01',
        'a_m_y_gay_01',
        'a_m_y_gay_02',
        'csb_g',
        'a_m_m_genfat_01',
        'a_m_m_genfat_02',
        'a_f_y_genhot_01',
        'a_f_o_genstreet_01',
        'a_m_o_genstreet_01',
        'a_m_y_genstreet_01',
        'a_m_y_genstreet_02',
        's_m_m_gentransport',
        'u_m_m_glenstank_01',
        'a_f_y_golfer_01',
        'a_m_m_golfer_01',
        'a_m_y_golfer_01',
        'u_m_m_griff_01',
        's_m_y_grip_01',
        'ig_groom',
        'csb_groom',
        'csb_grove_str_dlr',
        'cs_guadalope',
        'u_m_y_guido_01',
        'u_m_y_gunvend_01',
        'cs_gurk',
        'hc_hacker',
        's_m_m_hairdress_01',
        'ig_hao',
        'csb_hao',
        'a_m_m_hasjew_01',
        'a_m_y_hasjew_01',
        's_m_m_highsec_01',
        's_m_m_highsec_02',
        'a_f_y_hiker_01',
        'a_m_y_hiker_01',
        'a_m_m_hillbilly_01',
        'a_m_m_hillbilly_02',
        'u_m_y_hippie_01',
        'a_f_y_hippie_01',
        'a_m_y_hippy_01',
        'a_f_y_hipster_01',
        'a_m_y_hipster_01',
        'a_f_y_hipster_02',
        'a_m_y_hipster_02',
        'a_f_y_hipster_03',
        'a_m_y_hipster_03',
        'u_f_y_hotposh_01',
        'csb_hugh',
        'ig_hunter',
        'cs_hunter',
        'u_m_y_imporage',
        'csb_imran',
        'a_f_o_indian_01',
        'a_f_y_indian_01',
        'a_m_m_indian_01',
        'a_m_y_indian_01',
        'csb_jackhowitzer',
        'ig_janet',
        'cs_janet',
        'csb_janitor',
        's_m_m_janitor',
        'ig_jay_norris',
        'u_m_m_jesus_01',
        'a_m_y_jetski_01',
        'u_f_y_jewelass_01',
        'ig_jewelass',
        'cs_jewelass',
        'u_m_m_jewelsec_01',
        'u_m_m_jewelthief',
        'ig_jimmyboston',
        'cs_jimmyboston',
        'ig_jimmydisanto',
        'cs_jimmydisanto',
        'ig_joeminuteman',
        'cs_joeminuteman',
        'ig_johnnyklebitz',
        'cs_johnnyklebitz',
        'ig_josef',
        'cs_josef',
        'ig_josh',
        'cs_josh',
        'a_f_y_juggalo_01',
        'a_m_y_juggalo_01',
        'u_m_y_justin',
        'ig_karen_daniels',
        'cs_karen_daniels',
        'ig_kerrymcintosh',
        'g_m_m_korboss_01',
        'g_m_y_korean_01',
        'g_m_y_korean_02',
        'g_m_y_korlieut_01',
        'a_f_m_ktown_01',
        'a_f_o_ktown_01',
        'a_m_m_ktown_01',
        'a_m_o_ktown_01',
        'a_m_y_ktown_01',
        'a_f_m_ktown_02',
        'a_m_y_ktown_02',
        'ig_lamardavis',
        'cs_lamardavis',
        's_m_m_lathandy_01',
        'a_m_y_latino_01',
        'ig_lazlow',
        'cs_lazlow',
        'ig_lestercrest',
        'cs_lestercrest',
        'ig_lifeinvad_01',
        'cs_lifeinvad_01',
        's_m_m_lifeinvad_01',
        'ig_lifeinvad_02',
        's_m_m_linecook',
        'g_f_y_lost_01',
        'g_m_y_lost_01',
        'g_m_y_lost_02',
        'g_m_y_lost_03',
        's_m_m_lsmetro_01',
        'ig_magenta',
        'cs_magenta',
        's_f_m_maid_01',
        'a_m_m_malibu_01',
        'u_m_y_mani',
        'ig_manuel',
        'cs_manuel',
        's_m_m_mariachi_01',
        's_m_m_marine_01',
        's_m_y_marine_01',
        's_m_m_marine_02',
        's_m_y_marine_02',
        's_m_y_marine_03',
        'u_m_m_markfost',
        'ig_marnie',
        'cs_marnie',
        'cs_martinmadrazo',
        'ig_maryann',
        'cs_maryann',
        'ig_maude',
        'csb_maude',
        'csb_mweather',
        'a_m_y_methhead_01',
        'g_m_m_mexboss_01',
        'g_m_m_mexboss_02',
        'a_m_m_mexcntry_01',
        'g_m_y_mexgang_01',
        'g_m_y_mexgoon_01',
        'g_m_y_mexgoon_02',
        'g_m_y_mexgoon_03',
        'a_m_m_mexlabor_01',
        'a_m_y_mexthug_01',
        'player_zero',
        'ig_michelle',
        'cs_michelle',
        's_f_y_migrant_01',
        's_m_m_migrant_01',
        'u_m_y_militarybum',
        'ig_milton',
        'cs_milton',
        's_m_y_mime',
        'u_f_m_miranda',
        'u_f_y_mistress',
        'mp_f_misty_01',
        'ig_molly',
        'cs_molly',
        'a_m_y_motox_01',
        'a_m_y_motox_02',
        'cs_movpremf_01',
        'cs_movpremmale',
        'u_f_o_moviestar',
        'mp_g_m_pros_01',
        'ig_mrk',
        'cs_mrk',
        'ig_mrsphillips',
        'cs_mrsphillips',
        'ig_mrs_thornhill',
        'cs_mrs_thornhill',
        'a_m_y_musclbeac_01',
        'a_m_y_musclbeac_02',
        'ig_natalia',
        'cs_natalia',
        'ig_nervousron',
        'cs_nervousron',
        'ig_nigel',
        'cs_nigel',
        'a_m_m_og_boss_01',
        'ig_old_man1a',
        'cs_old_man1a',
        'ig_old_man2',
        'cs_old_man2',
        'ig_omega',
        'cs_omega',
        'ig_oneil',
        'ig_ortega',
        'csb_ortega',
        'csb_oscar',
        'ig_paige',
        'csb_paige',
        'a_m_m_paparazzi_01',
        'u_m_y_paparazzi',
        'ig_paper',
        'cs_paper',
        's_m_m_paramedic_01',
        'u_m_y_party_01',
        'u_m_m_partytarget',
        'ig_patricia',
        'cs_patricia',
        's_m_y_pestcont_01',
        'hc_driver',
        'hc_gunman',
        's_m_m_pilot_01',
        's_m_y_pilot_01',
        's_m_m_pilot_02',
        'g_m_y_pologoon_01',
        'g_m_y_pologoon_02',
        'a_m_m_polynesian_01',
        'a_m_y_polynesian_01',
        'ig_popov',
        'csb_popov',
        'u_f_y_poppymich',
        'csb_porndudes',
        's_m_m_postal_01',
        's_m_m_postal_02',
        'ig_priest',
        'cs_priest',
        'u_f_y_princess',
        's_m_m_prisguard_01',
        'u_m_y_prisoner_01',
        's_m_y_prisoner_01',
        'u_m_y_proldriver_01',
        'csb_prologuedriver',
        'u_f_o_prolhost_01',
        'a_f_m_prolhost_01',
        'a_m_m_prolhost_01',
        'u_f_m_promourn_01',
        'u_m_m_promourn_01',
        'u_m_m_prolsec_01',
        'csb_prolsec',
        'ig_prolsec_02',
        'cs_prolsec_02',
        'ig_ramp_gang',
        'csb_ramp_gang',
        'ig_ramp_hic',
        'csb_ramp_hic',
        'ig_ramp_hipster',
        'csb_ramp_hipster',
        'csb_ramp_marine',
        'ig_ramp_mex',
        'csb_ramp_mex',
        's_f_y_ranger_01',
        's_m_y_ranger_01',
        'ig_rashcosvki',
        'csb_rashcosvki',
        'csb_reporter',
        'u_m_m_rivalpap',
        'a_m_y_roadcyc_01',
        's_m_y_robber_01',
        'a_f_y_runner_01',
        'a_m_y_runner_01',
        'a_m_y_runner_02',
        'a_f_y_rurmeth_01',
        'a_m_m_rurmeth_01',
        'ig_russiandrunk',
        'cs_russiandrunk',
        'a_f_m_salton_01',
        'a_f_o_salton_01',
        'a_m_m_salton_01',
        'a_m_o_salton_01',
        'a_m_y_salton_01',
        'a_m_m_salton_02',
        'a_m_m_salton_03',
        'a_m_m_salton_04',
        'g_m_y_salvaboss_01',
        'g_m_y_salvagoon_01',
        'g_m_y_salvagoon_02',
        'g_m_y_salvagoon_03',
        'u_m_y_sbike',
        'a_f_y_scdressy_01',
        's_m_m_scientist_01',
        'ig_screen_writer',
        'csb_screen_writer',
        's_f_y_scrubs_01',
        's_m_m_security_01',
        's_f_y_sheriff_01',
        's_m_y_sheriff_01',
        's_f_m_shop_high',
        'mp_m_shopkeep_01',
        's_f_y_shop_low',
        's_m_y_shop_mask',
        's_f_y_shop_mid',
        'ig_siemonyetarian',
        'cs_siemonyetarian',
        'a_f_y_skater_01',
        'a_m_m_skater_01',
        'a_m_y_skater_01',
        'a_m_y_skater_02',
        'a_f_m_skidrow_01',
        'a_m_m_skidrow_01',
        'a_m_m_socenlat_01',
        'ig_solomon',
        'cs_solomon',
        'a_f_m_soucent_01',
        'a_f_o_soucent_01',
        'a_f_y_soucent_01',
        'a_m_m_soucent_01',
        'a_m_o_soucent_01',
        'a_m_y_soucent_01',
        'a_f_m_soucent_02',
        'a_f_o_soucent_02',
        'a_f_y_soucent_02',
        'a_m_m_soucent_02',
        'a_m_o_soucent_02',
        'a_m_y_soucent_02',
        'a_f_y_soucent_03',
        'a_m_m_soucent_03',
        'a_m_o_soucent_03',
        'a_m_y_soucent_03',
        'a_m_m_soucent_04',
        'a_m_y_soucent_04',
        'a_f_m_soucentmc_01',
        'u_m_m_spyactor',
        'u_f_y_spyactress',
        'u_m_y_staggrm_01',
        'a_m_y_stbla_01',
        'a_m_y_stbla_02',
        'ig_stevehains',
        'cs_stevehains',
        'a_m_y_stlat_01',
        'a_m_m_stlat_02',
        'ig_stretch',
        'cs_stretch',
        's_m_m_strperf_01',
        's_m_m_strpreach_01',
        'g_m_y_strpunk_01',
        'g_m_y_strpunk_02',
        's_m_m_strvend_01',
        's_m_y_strvend_01',
        'a_m_y_stwhi_01',
        'a_m_y_stwhi_02',
        'a_m_y_sunbathe_01',
        'a_m_y_surfer_01',
        's_f_m_sweatshop_01',
        's_f_y_sweatshop_01',
        'ig_talina',
        'ig_tanisha',
        'cs_tanisha',
        'ig_taocheng',
        'cs_taocheng',
        'ig_taostranslator',
        'cs_taostranslator',
        'u_m_o_taphillbilly',
        'u_m_y_tattoo_01',
        'a_f_y_tennis_01',
        'a_m_m_tennis_01',
        'ig_tenniscoach',
        'cs_tenniscoach',
        'ig_terry',
        'cs_terry',
        'cs_tom',
        'ig_tomepsilon',
        'cs_tomepsilon',
        'ig_tonya',
        'csb_tonya',
        'a_f_y_topless_01',
        'a_f_m_tourist_01',
        'a_f_y_tourist_01',
        'a_m_m_tourist_01',
        'a_f_y_tourist_02',
        'ig_tracydisanto',
        'cs_tracydisanto',
        'ig_trafficwarden',
        'csb_trafficwarden',
        'u_m_o_tramp_01',
        'a_f_m_tramp_01',
        'a_m_m_tramp_01',
        'a_m_o_tramp_01',
        'a_f_m_trampbeac_01',
        'a_m_m_trampbeac_01',
        'a_m_m_tranvest_01',
        'a_m_m_tranvest_02',
        'player_two',
        's_m_m_trucker_01',
        'ig_tylerdix',
        'csb_undercover',
        's_m_m_ups_01',
        's_m_m_ups_02',
        's_m_y_uscg_01',
        'g_f_y_vagos_01',
        'mp_m_g_vagfun_01',
        'ig_vagspeak',
        'csb_vagspeak',
        's_m_y_valet_01',
        'a_m_y_vindouche_01',
        'a_f_y_vinewood_01',
        'a_m_y_vinewood_01',
        'a_f_y_vinewood_02',
        'a_m_y_vinewood_02',
        'a_f_y_vinewood_03',
        'a_m_y_vinewood_03',
        'a_f_y_vinewood_04',
        'a_m_y_vinewood_04',
        'cs_wade',
        's_m_y_waiter_01',
        'ig_chengsr',
        'cs_chengsr',
        'u_m_m_willyfist',
        's_m_y_winclean_01',
        's_m_y_xmech_01',
        's_m_y_xmech_02',
        'a_f_y_yoga_01',
        'a_m_y_yoga_01',
        'ig_zimbor',
        'cs_zimbor',
        'a_f_y_femaleagent',
        'g_f_importexport_01',
        'g_m_importexport_01',
        'ig_agent',
        'ig_malc',
        'mp_f_cardesign_01',
        'mp_f_chbar_01',
        'mp_f_counterfeit_01',
        'mp_f_execpa_01',
        'mp_f_execpa_02',
        'mp_f_forgery_01',
        'mp_f_helistaff_01',
        'mp_f_meth_01',
        'mp_f_weed_01',
        'mp_m_cocaine_01',
        'mp_m_counterfeit_01',
        'mp_m_execpa_01',
        'mp_m_forgery_01',
        'mp_m_meth_01',
        'mp_m_securoguard_01',
        'mp_m_waremech_01',
        'mp_m_weapexp_01',
        'mp_m_weapwork_01',
        'mp_m_weed_01',
        's_m_y_xmech_02_mp',
        'u_f_y_corpse_01',
        'u_m_m_streetart_01',
        'ig_lestercrest_2',
        'ig_avon',
        'mp_m_avongoon',
        'mp_m_bogdangoon',
        'u_m_y_corpse_01',
    }
}
