RegisterNetEvent("esx_drilltime:effects:client:drunk")
AddEventHandler("esx_drilltime:effects:client:drunk", function()
    Drunkffect()
end)

RegisterNetEvent("esx_drilltime:effects:client:drug")
AddEventHandler("esx_drilltime:effects:client:drug", function()
    DrugEffect()
end)


function Drunkffect()
    local playerPed = GetPlayerPed(-1)
    local playerPed = PlayerPedId()
    local anim = "MOVE_M@DRUNK@VERYDRUNK"
    RequestAnimSet(anim) 
    while not HasAnimSetLoaded(anim) do
      Citizen.Wait(0)
    end    
    ClearPedTasksImmediately(playerPed)
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, anim, true)
    SetPedIsDrunk(playerPed, true)
    SetTimecycleModifier("spectator5")
    AnimpostfxPlay("SuccessMichael", 10000001, true)
    ShakeGameplayCam("FAMILY5_DRUG_TRIP_SHAKE", 1.5)
    SetEntityHealth(GetPlayerPed(-1), 200)
    Citizen.Wait(120000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)		
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("FAMILY5_DRUG_TRIP_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
end

function DrugEffect()
    local playerPed = GetPlayerPed(-1)
    local playerPed = PlayerPedId()
    local anim = "MOVE_M@DRUNK@MODERATEDRUNK_HEAD_UP"
    RequestAnimSet(anim) 
    while not HasAnimSetLoaded(anim) do
        Citizen.Wait(0)
    end    
    ClearPedTasksImmediately(playerPed)
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, anim, true)
    SetPedIsDrunk(playerPed, true)
    SetTimecycleModifier("spectator5")
    AnimpostfxPlay("Rampage", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 1.5)
    StartScreenEffect('PeyoteEndOut', 0, true)
    StartScreenEffect('Dont_tazeme_bro', 0, true)
    StartScreenEffect('MP_race_crash', 0, true)
    SetEntityHealth(GetPlayerPed(-1), 200)
    Citizen.Wait(120000)
    SetPedMoveRateOverride(PlayerId(),1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)		
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    StopScreenEffect('PeyoteEndOut')
    StopScreenEffect('Dont_tazeme_bro')
    StopScreenEffect('MP_race_crash')
end