--[[
 Decrypt & Fix by FXEZ
 discord.gg/fxez
]]
-- Decrypt & Fixed by FXEZ | discord.gg/fxez
-- Copyright (c) FXEZ — https://discord.gg/fxez

if GetResourceState('qs-housing') == 'started' then
    local shells = {
        {model = 'k4_motel1_shell',              stash = {maxweight = 800000, slots = 4}},
        {model = 'standardmotel_shell',          stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_trailer',                stash = {maxweight = 800000, slots = 4}},
        {model = 'default_housing3_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'furnitured_motel',             stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_sandyhouse1_shell',      stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_trap_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_trap2_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_v16low',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'default_housing6_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_lester',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'default_housing1_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_hoodhouse1_shell',       stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_medium3',                stash = {maxweight = 800000, slots = 4}},
        {model = 'medium_housing3_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_hotel1_shell',              stash = {maxweight = 800000, slots = 4}},
        {model = 'modernhotel_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_hotel2_shell',              stash = {maxweight = 800000, slots = 4}},
        {model = 'modernhotel2_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_hotel3_shell',              stash = {maxweight = 800000, slots = 4}},
        {model = 'modernhotel3_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_apartment_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_motel1_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_motel2_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'kambi_emptyhouse1',            stash = {maxweight = 800000, slots = 4}},
        {model = 'kambi_furnishedhouse1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'furnitured_lowapart',          stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_trevor',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'default_housing4_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_medium2',                stash = {maxweight = 800000, slots = 4}},
        {model = 'medium_housing2_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_v16mid',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'furnitured_midapart',          stash = {maxweight = 800000, slots = 4}},
        {model = 'default_housing5_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_frankaunt',              stash = {maxweight = 800000, slots = 4}},
        {model = 'medium_housing1_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_house4_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_motel2_shell',              stash = {maxweight = 800000, slots = 4}},
        {model = 'classicmotel_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_motel3_shell',              stash = {maxweight = 800000, slots = 4}},
        {model = 'highendmotel_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_loft1_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'luxury_housing1_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'luxury_housing3_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'luxury_housing2_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'luxury_housing4_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'safehouse_k4mb1',              stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_ranch',                  stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_modern_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_highendv2',              stash = {maxweight = 800000, slots = 4}},
        {model = 'deluxe_housing2_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_palhouse1_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'classichouse_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'classichouse2_shell',          stash = {maxweight = 800000, slots = 4}},
        {model = 'classichouse3_shell',          stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_classic4_shell',         stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_classic5_shell',         stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_classic6_shell',         stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_farmhouse_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_casinohotel_shell',      stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_loft2_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'vinewood_housing3_k4mb1',      stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_banham',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'modern_housing3_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_house1_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_highend',                stash = {maxweight = 800000, slots = 4}},
        {model = 'deluxe_housing1_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_apartment1',             stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_apartment2',             stash = {maxweight = 800000, slots = 4}},
        {model = 'highend_housing1_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'highend_housing2_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_house2_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_house3_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'default_housing2_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_apa1_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_apa2_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_apa3_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'vinewood_housing2_k4mb1',      stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_banham_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_loft3_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_penthouse2_shell',       stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_mansion_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_mansion2_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'k4_mansion3_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_apartment3',             stash = {maxweight = 800000, slots = 4}},
        {model = 'highend_housing3_k4mb1',       stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_michael',                stash = {maxweight = 800000, slots = 4}},
        {model = 'deluxe_housing3_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_westons2',               stash = {maxweight = 800000, slots = 4}},
        {model = 'modern_housing2_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_beachhouse_shell',       stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_westons',                stash = {maxweight = 800000, slots = 4}},
        {model = 'modern_housing1_k4mb1',        stash = {maxweight = 800000, slots = 4}},
        {model = 'vinewood_housing1_k4mb1',      stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_penthouse_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'manor_housing1_k4mb1',         stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_mansion_shell',          stash = {maxweight = 800000, slots = 4}},
        {model = 'container_shell',              stash = {maxweight = 800000, slots = 4}},
        {model = 'container2_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_acid_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'stashhouse2_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'stashhouse3_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_warehouse3',             stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_store1',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_warehouse1',             stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_coke1',                  stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_drug_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_warehouse_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_biker3_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'gunworkshop_k4mb1',            stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_weed',                   stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_warehouse2',             stash = {maxweight = 800000, slots = 4}},
        {model = 'warehouse_k4mb1',              stash = {maxweight = 800000, slots = 4}},
        {model = 'stashhouse_shell',             stash = {maxweight = 800000, slots = 4}},
        {model = 'stashhouse1_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_biker1_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_biker2_shell',           stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_basement1_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_basement2_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_basement3_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_basement4_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_basement5_shell',        stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_hoodhouse2_shell',       stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_garages',                stash = {maxweight = 800000, slots = 4}},
        {model = 'new_garages2_k4mb1',           stash = {maxweight = 800000, slots = 4}},
        {model = 'new_garages3_k4mb1',           stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_garagem',                stash = {maxweight = 800000, slots = 4}},
        {model = 'new_garages4_k4mb1',           stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_garagel',                stash = {maxweight = 800000, slots = 4}},
        {model = 'new_garages1_k4mb1',           stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_office1',                stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_office2',                stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_furnishedoffice1_shell', stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_furnishedoffice2_shell', stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_furnishedoffice4_shell', stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_officebig',              stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_furnishedoffice3_shell', stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_furnishedoffice5_shell', stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_barber',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_gunstore',               stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_store2',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_store3',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_acid2_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_coke2',                  stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_meth',                   stash = {maxweight = 800000, slots = 4}},
        {model = 'k4coke_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4meth_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4weed_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'shell_weed2',                  stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_laundry_shell',          stash = {maxweight = 800000, slots = 4}},
		{model = 'k4mb1_banham2_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_beachhouse2_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_bunkersilo_shell',            stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_house1paleto_shell',                  stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_mansion1modern_shell',                   stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_vw_house4_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_villa1_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_mansion2_shell',                 stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_mansion3_shell',                  stash = {maxweight = 800000, slots = 4}},
        {model = 'k4mb1_manor2_shell',          stash = {maxweight = 800000, slots = 4}},
    }
    
    for _, shell in ipairs(shells) do
        exports['qs-housing']:AddShell({
            model = shell.model,
            stash = shell.stash
        })
    end
    print("[DEBUG]: Import of AllShellsSubPack completed")
end